apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strigus
  name: strigus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strigus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strigus
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
        limits:
          cpu: 0.5
          memory: 128Mi
        requests:
          cpu: 0.25
          memory: 64Mi
status: {}
